config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'

  resources :items, only: [:index]
  resources :asks, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask.rb
class Ask < ApplicationRecord
  # validations
  validates :username, presence: true
  validates :item_id, presence: true
  validates :title, presence: true
  validates :time, presence: true
  validates :item_type, presence: true
end

app/models/concerns/hackernews_api.rb
class HackernewsAPI

  # def get_all_results
  #   if Rails.env.development?
  #     return $hackernewsapi_api_result if $hackernewsapi_api_result
  #     $hackernewsapi_api_result = call_api
  #     return $hackernewsapi_api_result
  #   else
  #     return call_api
  #   end
  # end

  def create_item

    # STEP 1: Call 500 stories from Hackernews and parse its body
    url = "https://hacker-news.firebaseio.com/v0/newstories/"

    @results = HTTParty.get("#{url}.json?print=pretty")
    @top_stories = JSON.parse(@results.body)

    # STEP 2: Setup to store the new stories in an empty array
    new_stories = []

    # STEP 3: For each story(it's an id), store the 'item' into the new_stories array
    @top_stories.each do |story|
      item = HTTParty.get("https://hacker-news.firebaseio.com/v0/item/#{story}.json?print=pretty")

      new_stories << item
    end

    # response = get_all_results

    new_stories.each do |element|
      kids = element['kids']
      new_item = Item.create(
        username: element['by'],
        descendants: element['descendants'],
        item_id: element['id'],
        score: element['score'],
        time: element['time'],
        title: element['title'],
        item_type: element['type'],
        url: element['url'],
        content: element['text']
      )
    end
  end

  def create_ask
    # STEP 1: Call 500 stories from Hackernews and parse its body
    url = "https://hacker-news.firebaseio.com/v0/askstories/"

    @results = HTTParty.get("#{url}.json?print=pretty")
    @ask_stories = JSON.parse(@results.body)

    # STEP 2: Setup to store the new stories in an empty array
    ask_stories = []

    # STEP 3: For each story(it's an id), store the 'item' into the ask_stories array
    @ask_stories.each do |ask|
      item = HTTParty.get("https://hacker-news.firebaseio.com/v0/item/#{ask}.json?print=pretty")

      ask_stories << item
    end

    ask_stories.each do |element|
      new_item = Ask.create(
        username: element['by'],
        descendants: element['descendants'],
        item_id: element['id'],
        score: element['score'],
        time: element['time'],
        title: element['title'],
        item_type: element['type'],
        url: element['url'],
        content: element['text']
      )
    end
  end

  # Invoke this method to start calling the HackernewsAPI and store the new stories into the database
  def create_db
    create_item
    create_ask
  end

  def destroy_and_create_db
    Item.destroy_all
    Ask.destroy_all
  end

end

app/models/item.rb
class Item < ApplicationRecord
  # validations
  validates :username, presence: true
  validates :item_id, presence: true, uniqueness: true
  validates :title, presence: true
  validates :time, presence: true
  validates :item_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  def index
    @asks = Ask.all.order(:time).paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order(:time).paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/asks/index.html.erb
<div class="container">
  <div class="list-group">
    <% @asks.each do |ask| %>

      <%=link_to("http://news.ycombinator.com/item?id=#{ask.item_id}", class:"list-group-item list-group-item-action flex-column align-items-start", :target => "_blank") do %>

      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= ask.username %></h5>
        <small><%= time_ago_in_words(ask.time) %></small>
      </div>
      <p class="mb-1"><%= ask.title %></p>
      <small class="text-muted"><%= ask.descendants%> comment</small>

      <% end %>

    <% end %>

  </div>

</div>

app/views/items/index.html.erb
<!-- <div class="container-fluid">
  <div class="row">
    <div class="col-md-12"> -->

<div class="container">
  <div class="list-group">
    <% @items.each do |item| %>

      <%=link_to("http://news.ycombinator.com/item?id=#{item.item_id}", class:"list-group-item list-group-item-action flex-column align-items-start", :target => "_blank") do %>

      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= item.username %></h5>
        <small><%= time_ago_in_words(item.time) %></small>
      </div>
      <p class="mb-1"><%= item.title %></p>
      <small class="text-muted"><%= item.descendants%> comment</small>

      <% end %>

    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackernews</title>
    <%= csrf_meta_tags %>

    <!-- BootstrapCDN CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<%= root_path %>">HACKERNEWS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<%=asks_path %>">Asks <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>

  <%= will_paginate(@items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'd-flex justify-content-center') %>

  <body>
    <%= yield %>


  <%= will_paginate(@items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'd-flex justify-content-center') %>

  <!-- Footer -->
  <footer class="position-sticky py-3 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Lan Phan | Hacknews Assignment </p>
  </div>
  </footer>

    <!-- BootstrapCDN JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  </body>
</html>